### ISSUE TITLE
does not listen

### ISSUE THREAD

**Issue by whitehat-coders** [ahmadbrainworks/tron-events#1]
The code does not look like it listens for events. instead it fetches blocks based on GET request params. correct me if I am wrong

**Comment by ahmadbrainworks** [comment]
Yes that's what it does.
I stopped working on it.

**Comment by whitehat-coders** [comment]
ok. setting up a small crypto exchange. looking for the best implementation for managing user wallets for EVM blockchains and TRON. receiving and relaying funds to hot wallet and also managing private keys

Any recommendations from  your end?

**Comment by ahmadbrainworks** [comment]
Yes, let me take you with this repo explanation.

What it does, is watch every new block that is mined then filter any TRC 20 token(contract) address that you gave it. 


For EVM chains, the likes ETH, POLYGON, FTM, BSC check this repo https://github.com/ahmadbrainworks/fiddi it watches the based token(e.g on ETH chain it watches for ETH transactions that occurs on any address that you give the tool to watch for it's ETH transaction) and it'll notify your webhook whenever a transaction occurs.


And for contracts(tokens), you can use the websocket protocol it works perfect.

**Comment by whitehat-coders** [comment]
one challenge. fiddi is rust. would have preferred JS. this is for wallet-notify aspect

what about pooling funds in a hot wallet. is there a work around? will i need to credit each users wallet with the chains native token before i can move user funds to hot wallet?

Best way to handle private key for each user?

**Comment by ahmadbrainworks** [comment]
I got you now... you want an insight about how the CEX will work.

**Comment by ahmadbrainworks** [comment]
- start with generating wallet address and encrypt the private keys(for users), and store the encrypted keys on your db.
- whenever you want to move funds from user wallet to HOT wallet, send gas fee(fee) to that address and move the funds to hot wallet.

**Comment by whitehat-coders** [comment]
thanks thought as much.

wish i had some open source code that will handle retrieving fund this way

**Comment by ahmadbrainworks** [comment]
retrieving like, the funds distribution from users wallet to HOT wallet??

**Comment by ahmadbrainworks** [comment]
there are many resources out there for transfer of funds/coins.

**Comment by whitehat-coders** [comment]
Yes. but its not straightforward. need to wait for confirmations etc. in between sending in your native coin and retrieving. will need careful implementation. also knowing what amount of native coin to send in for fees depending on network activity.

**Comment by ahmadbrainworks** [comment]
for amount of fees, ou can call a web4 function  "estimateGas()" to estimate gas fee.

for transactions confirmation, e.g BSC let's say 20 confirmation, you can record the transaction on your db, after the transaction is confirmed then credit the user.

**Comment by whitehat-coders** [comment]
ok. listening for native token is not same as listening to events for contract tokens right?

**Comment by whitehat-coders** [comment]
looking to support tron and BSC initially. would you recommend i setup my own nodes for this purposes?

**Comment by ahmadbrainworks** [comment]
yes using your nodes is better.

for tron you need like, 1TB+ storage, and BSC like 500GB+

**Comment by ahmadbrainworks** [comment]
> ok. listening for native token is not same as listening to events for contract tokens right?

yes are not same.

native token(coin) omits no events, you need to look for new blocks and filter those for native token and check those who are for your address and log them. but [fiddi ](https://github.com/ahmadbrainworks/fiddi) can do all of that for you.

**Comment by whitehat-coders** [comment]
> yes using your nodes is better.
> 
> for tron you need like, 1TB+ storage, and BSC like 500GB+

Even when I only need this for event listening. Can't I run a light node with minimal hardware vps.  A 1tb vps would cost an arm

**Comment by ahmadbrainworks** [comment]
BSC have light node, TRON does not have

**Comment by whitehat-coders** [comment]
> BSC have light node, TRON does not have

Thanks very much for your time

**Comment by ahmadbrainworks** [comment]
you are welcome.

**Comment by ahmadbrainworks** [comment]
> BSC have light node, TRON does not have

for TRON it have a community nodes, apis e.g trongrid that you can use, but they have rate limit issues.

and for BS you can use the public nodes for broadcasting transactions, and for native token deposit using fiddi, but for BEP20 you need ws connection which the public node does not have it enabled.
